apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: KenTest01
  
  description: KenTest01
  
  annotations:
    github.com/project-slug: defra-adp-sandpit/KenTest01
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/defra-adp-sandpit/KenTest01
      title: GitHub Repository
      icon: github

spec:
  type: frontend
  lifecycle: alpha
  owner: "group:default/adp"
  